version: "3.8"

services:
  # Development environment
  frontend-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - app_network

  # Production environment
  frontend:
    profiles:
      - prod
    container_name: app_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - app_network

# Define a shared network
networks:
  app_network:
    driver: bridge
