services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - postgres
    ports:
      - '6001:6001'
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  # Define the named volume for PostgreSQL data persistence
  postgres_data:   
