services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '6001:6001'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - default
      - supabase_default

networks:
  supabase_default:
    external: true
