services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - postgres
    ports:
      - '6001:6001'
    env_file:
      - .env
    volumes:
      - generated_files:/app/generatedFiles
      - uploaded_files:/app/uploadedFiles

volumes:
  postgres_data:
  generated_files:
  uploaded_files:
